server:
  port: 7780 # 端口

spring:
  application:
    name: config-client # 应用名称


# 自定义配置
name: config-client-prod
# 对称加密
password: '{cipher}43cc519fed25304d8b69b68f0ba6b3fe5914a235b555cb9ae7aac66918110019'
# 非对称加密
#password: '{cipher}AQAhjhLR3rclkAZhnkrg08BhKV7vu04gzcD9oZBlKnFCp5VnPdtrqDomZaBg0/a+8zVBiOKMcuOw1yaXvlnkmcTh3YJy+AO0dQanhQ6V6qgRPXZnaXSPecZo8ZTD2i7o/38jHFzlqnTC3AiRvASe71HSbgGx83XoImuWSu3/J7FhXLwV6ZOISL7O+oMeSLgcaWhBhAdpfU7jH8DqPcgHltWIIN8YP2D4V5GQaegtUs8BGiR1aSkdVC6WIy4tpYAQhBbC7oYsP2WtBPrhq8F/Num0JGnTurkMWBI+VSYMPBf2za0m9RDJDWWRyDk4DLIixbAC5STE6EpKHoyllr2NLcz6kk+c9TRDsRDyB/wzSBhJfcOzP9x5XPCK3oTMy91RM4c='
priority: pord_17:17
