server:
  port: 7780 # 端口

spring:
  application:
    name: config-client # 应用名称

# 自定义配置
name: config-client-prod
# 对称加密
# password: '{cipher}727148f4aa2072246147b1a9ca6a2758a3a5658f8216f7cae93721466f1f7046'
# 非对称加密
password: '{cipher}AQAouG/XR2W+fwOCFvL8BTpKgjLh6iFUWKRXPX97MRJC8u4dXgYXuGPYDi3kW36XoSH/tDxn2ElHZndOrhkkk4DGC43boK7X2If1nzQLMWIEcoGFieq8/VBEHbrhUGavMm76aAXKq2qebcx+85kdopft3fSQJ796Gjj5BQ6LZk8N0o2j2QSIIQ8c32SKP7aaAwGp67WSIWXt2RfWjH+vls178ZtYDLTLJ/AZg3PPzxN4Tyu6dQRTLp9T/KktL6RSVEpg7Mo9wpPxUGa+MRhvlEP/0w8x7fciYLjnIQ0F20q8JW8JaKImpyMjLo4mOCVk818FsRYjw9pDd75WQtcN4RDVIOW9k8dbGEbRPX/9vuW4/iwPbUesxkUpaOrWEq19Un+wqXpt9ycBSFib6efFtG3i'
